<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WTlTne3' shared service.

return $this->privates['.service_locator.WTlTne3'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('query' => function (): \App\service\DataService {
    return ($this->privates['App\service\DataService'] ?? $this->load('getDataServiceService.php'));
}));
