<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_paginator.templating.helper.pagination' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-paginator-bundle/Templating/PaginationHelper.php';

return $this->privates['knp_paginator.templating.helper.pagination'] = new \Knp\Bundle\PaginatorBundle\Templating\PaginationHelper(($this->privates['knp_paginator.helper.processor'] ?? $this->getKnpPaginator_Helper_ProcessorService()), ($this->privates['templating.engine.php'] ?? $this->load('getTemplating_Engine_PhpService.php')));
