<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMxy5DE\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMxy5DE/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOMxy5DE.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerOMxy5DE\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerOMxy5DE\srcProdProjectContainer(array(
    'container.build_hash' => 'OMxy5DE',
    'container.build_id' => '206130ea',
    'container.build_time' => 1539679335,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMxy5DE');
