<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP0GFVP4\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP0GFVP4/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerP0GFVP4.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerP0GFVP4\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerP0GFVP4\srcProdProjectContainer(array(
    'container.build_hash' => 'P0GFVP4',
    'container.build_id' => '2f37f16b',
    'container.build_time' => 1539344834,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerP0GFVP4');
