<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7f2QzS\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7f2QzS/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC7f2QzS.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerC7f2QzS\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerC7f2QzS\srcProdProjectContainer(array(
    'container.build_hash' => 'C7f2QzS',
    'container.build_id' => '8cd68f2e',
    'container.build_time' => 1541700979,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7f2QzS');
