<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.q4iV3.e.App\Entity\CjOffres' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.q4iV3.e": it references class "App\\Entity\\CjOffres" but no such service exists.');
