<?php

namespace Proxies\__CG__\App\Entity\Customer;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\Customer\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'entreprise_id', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'plainPassword', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'smsc', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'securite', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'partenairePrincipal_id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'entreprise_id', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'plainPassword', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'tel', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'smsc', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'securite', '' . "\0" . 'App\\Entity\\Customer\\User' . "\0" . 'partenairePrincipal_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrepriseId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrepriseId', []);

        return parent::getEntrepriseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrepriseId(?int $entreprise_id): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrepriseId', [$entreprise_id]);

        return parent::setEntrepriseId($entreprise_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(?string $nom): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(?string $prenom): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(?string $password): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword(?string $plainPassword): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$plainPassword]);

        return parent::setPlainPassword($plainPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt(?string $salt): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel(?string $tel): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmsc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmsc', []);

        return parent::getSmsc();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmsc(?string $smsc): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmsc', [$smsc]);

        return parent::setSmsc($smsc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(?\DateTimeInterface $dateCreation): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(?string $titre): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(?int $statut): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(?int $etat): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecurite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecurite', []);

        return parent::getSecurite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecurite(?int $securite): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecurite', [$securite]);

        return parent::setSecurite($securite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartenairePrincipalId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartenairePrincipalId', []);

        return parent::getPartenairePrincipalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartenairePrincipalId(?int $partenairePrincipal_id): \App\Entity\Customer\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartenairePrincipalId', [$partenairePrincipal_id]);

        return parent::setPartenairePrincipalId($partenairePrincipal_id);
    }

}
