<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIg2uVHZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIg2uVHZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIg2uVHZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIg2uVHZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIg2uVHZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ig2uVHZ',
    'container.build_id' => '8bb1f24d',
    'container.build_time' => 1541680668,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIg2uVHZ');
