<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFuzJtIP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFuzJtIP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFuzJtIP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFuzJtIP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFuzJtIP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FuzJtIP',
    'container.build_id' => '9816b23b',
    'container.build_time' => 1540293733,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFuzJtIP');
